name: Superstore CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t superstore-app:${{ github.sha }} .
          docker tag superstore-app:${{ github.sha }} mydockerhub/superstore-app:latest
          docker push mydockerhub/superstore-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Kubernetes Deployment
        run: |
          sed -i 's|IMAGE_TAG|${{ github.sha }}|g' k8s/deployment.yaml
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s/deployment.yaml
          git commit -m "Update deployment to ${{ github.sha }}"
          git push origin main
